version: '0.0.3.1.{build}'
image:
  - Visual Studio 2019
  - Ubuntu
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  - cmd: cd
  # Display minimal restore text
  - cmd: dotnet restore ./StrobeNet.sln --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./StrobeNet.sln
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  # restore packages and run
  dotnet test ./StrobeNet.Tests/StrobeNet.Tests.csproj -c Release -f netcoreapp2.0
on_finish :
  # any cleanup in here
deploy: off
